'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {inr} from '@/lib/currency';
import {label} from '@/lib/utils';
import {AlertTriangle,CheckCircle2,Search,ShieldCheck,XCircle} from 'lucide-react';

export type ApprovalRow={id:string;createdAt:string;customer:string;failureReason:string;amount:number;score:number;risk:string;contacts:number;expectedValue:number;action:string;status:string;reason:string;diagnosis:string|null;analysisSource:string|null};
type Confirmation={kind:'approve'|'reject'|'bulk';id?:string}|null;

export function ApprovalQueue({initialRows}:{initialRows:ApprovalRow[]}){
 const [rows,setRows]=useState(initialRows),[query,setQuery]=useState(''),[sort,setSort]=useState('score'),[risk,setRisk]=useState('ALL'),[selected,setSelected]=useState<string[]>([]),[actions,setActions]=useState<Record<string,string>>({}),[confirmation,setConfirmation]=useState<Confirmation>(null),[reason,setReason]=useState('Not suitable for recovery'),[pending,setPending]=useState(false),[message,setMessage]=useState('');
 const visible=useMemo(()=>rows.filter(row=>(risk==='ALL'||row.risk===risk)&&`${row.customer} ${row.failureReason} ${row.action}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='amount'?b.amount-a.amount:sort==='recent'?Date.parse(b.createdAt)-Date.parse(a.createdAt):b.score-a.score),[rows,query,sort,risk]);
 const bulkEligible=visible.filter(row=>row.action!=='NEEDS_REVIEW'&&row.status!=='APPROVED').map(row=>row.id);
 async function submit(){if(!confirmation)return;setPending(true);setMessage('');try{
   if(confirmation.kind==='bulk'){
     const response=await fetch('/api/approvals/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:selected})});const body=await response.json();if(!response.ok)throw Error(body.error);const approvedIds=body.results.filter((x:{status:string})=>x.status==='APPROVED').map((x:{id:string})=>x.id);setRows(current=>current.filter(row=>!approvedIds.includes(row.id)));setSelected([]);setMessage(`${body.approved} approved; ${body.blocked} blocked by current safeguards.`);
   }else{
     const id=confirmation.id!;const kind=confirmation.kind;const response=await fetch(`/api/recoveries/${id}/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(kind==='reject'?{reason}:{action:actions[id]??rows.find(row=>row.id===id)?.action})});const body=await response.json();if(!response.ok)throw Error(body.error);setRows(current=>current.filter(row=>row.id!==id));setSelected(current=>current.filter(value=>value!==id));setMessage(kind==='reject'?'Case rejected and audited.':'Case approved after server-side safety checks.');
   }
 }catch(error){setMessage(error instanceof Error?error.message:'Action failed');}finally{setPending(false);setConfirmation(null);}}
 return <div className="space-y-4">
   {message&&<div className="callout callout-info"><CheckCircle2 size={15}/><p>{message}</p></div>}
   {confirmation&&<div className="callout callout-warning items-start"><AlertTriangle size={16} className="mt-0.5"/><div className="flex-1"><p className="font-semibold">Confirm consequential decision</p><p className="mt-1 text-xs">{confirmation.kind==='bulk'?`Approve ${selected.length} eligible cases. Every case will be revalidated independently.`:confirmation.kind==='reject'?'Reject this case and permanently remove it from the active recovery queue.':'Approve the selected action after a fresh policy check.'}</p>{confirmation.kind==='reject'&&<input className="input mt-3" value={reason} onChange={event=>setReason(event.target.value)} aria-label="Rejection reason"/>}<div className="mt-3 flex gap-2"><button className={confirmation.kind==='reject'?'btn-danger':'btn-warning'} disabled={pending||confirmation.kind==='reject'&&reason.trim().length<3} onClick={()=>void submit()}>{pending?'Working…':'Confirm'}</button><button className="btn-ghost" disabled={pending} onClick={()=>setConfirmation(null)}>Cancel</button></div></div></div>}
   <div className="card card-static overflow-hidden">
     <div className="flex flex-wrap gap-3 border-b border-slate-200 bg-slate-50/60 p-4"><div className="relative min-w-[220px] flex-1"><Search size={14} className="absolute left-3 top-2.5 text-slate-400"/><input className="input py-1.5 pl-8 text-xs" placeholder="Customer, failure, action…" value={query} onChange={event=>setQuery(event.target.value)}/></div><select className="select-input w-auto text-xs" value={risk} onChange={event=>setRisk(event.target.value)}><option value="ALL">All risk bands</option><option value="HIGH">High risk</option><option value="LOW">Low risk</option><option value="STANDARD">Standard risk</option></select><select className="select-input w-auto text-xs" value={sort} onChange={event=>setSort(event.target.value)}><option value="score">Highest score</option><option value="amount">Highest amount</option><option value="recent">Most recent</option></select><button className="btn-primary" disabled={!selected.length} onClick={()=>setConfirmation({kind:'bulk'})}><ShieldCheck size={14}/>Approve selected ({selected.length})</button></div>
     {visible.length?<div className="overflow-x-auto"><table className="data-table"><thead><tr><th><input type="checkbox" aria-label="Select all eligible cases" checked={bulkEligible.length>0&&bulkEligible.every(id=>selected.includes(id))} onChange={event=>setSelected(event.target.checked?bulkEligible:[])}/></th><th>Case</th><th>Value and risk</th><th>Decision evidence</th><th>Action</th><th>Controls</th></tr></thead><tbody>{visible.map(row=>{const eligible=row.action!=='NEEDS_REVIEW'&&row.status!=='APPROVED';return <tr key={row.id}><td><input type="checkbox" disabled={!eligible} checked={selected.includes(row.id)} onChange={event=>setSelected(current=>event.target.checked?[...current,row.id]:current.filter(id=>id!==row.id))}/></td><td><Link className="font-semibold text-slate-900 hover:text-brand-600" href={`/recoveries/${row.id}`}>{row.customer}</Link><p className="mt-1 text-xs text-slate-500">{label(row.failureReason)} · score {row.score}</p></td><td><p className="font-semibold tabular-nums">{inr(row.amount)}</p><p className="text-xs text-emerald-700">Expected value {inr(row.expectedValue)}</p><p className="text-xs text-slate-500">{row.risk} risk · {row.contacts}/2 contacts</p></td><td className="max-w-xs"><p className="text-xs font-medium text-amber-800">Policy: {row.reason}</p><p className="mt-1 line-clamp-2 text-xs text-slate-500">AI ({row.analysisSource?label(row.analysisSource):'not run'}): {row.diagnosis??'No saved diagnosis. The deterministic decision remains authoritative.'}</p></td><td><select className="select-input min-w-[180px] text-xs" value={actions[row.id]??(row.action==='NEEDS_REVIEW'?'SEND_PAYMENT_UPDATE_LINK':row.action)} onChange={event=>setActions(current=>({...current,[row.id]:event.target.value}))}><option value="SEND_PAYMENT_UPDATE_LINK">Send payment update link</option><option value="RETRY_LATER">Schedule one retry</option></select>{actions[row.id]&&actions[row.id]!==row.action&&<p className="mt-1 text-[11px] text-amber-700">Modified from {label(row.action)}</p>}</td><td><div className="flex flex-col gap-2"><button className="btn-success py-1.5 text-xs" onClick={()=>setConfirmation({kind:'approve',id:row.id})}><CheckCircle2 size={13}/>Approve</button><button className="btn-ghost py-1.5 text-xs text-red-700" onClick={()=>setConfirmation({kind:'reject',id:row.id})}><XCircle size={13}/>Reject</button></div></td></tr>})}</tbody></table></div>:<div className="p-14 text-center text-sm text-slate-500">No approval cases match the current filters.</div>}
   </div>
 </div>;
}
