'use client';
import {useState} from 'react';
import {CheckCircle2,Play,ShieldAlert} from 'lucide-react';
import type {SafetyScenario} from '@/domain/recovery/safety-lab-service';

const safetyScenarios:SafetyScenario[]=['CONCURRENT_WEBHOOK','DUPLICATE_EXECUTION','PROVIDER_TIMEOUT','STALE_RESERVATION','INVALID_SIGNATURE','UNSAFE_RETRY','KILL_SWITCH','CONTACT_LIMIT'];

type Run={id:string;scenario:string;injected:string;expectedInvariant:string;timeline:string;requestsReceived:number;accepted:number;duplicatesRejected:number;providerActions:number;finalState:string;auditEvents:number;passed:boolean;createdAt:string|Date};
const names:Record<SafetyScenario,string>={CONCURRENT_WEBHOOK:'10 concurrent webhooks',DUPLICATE_EXECUTION:'Duplicate execution',PROVIDER_TIMEOUT:'Provider timeout',STALE_RESERVATION:'Stale reservation',INVALID_SIGNATURE:'Invalid signature',UNSAFE_RETRY:'Unsafe retry',KILL_SWITCH:'Kill switch',CONTACT_LIMIT:'Contact limit'};
export function SafetyLab({initial}:{initial:Run[]}){const [runs,setRuns]=useState(initial),[busy,setBusy]=useState(''),[error,setError]=useState('');async function run(scenario:SafetyScenario){setBusy(scenario);setError('');try{const r=await fetch('/api/safety-lab',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({scenario})});const b=await r.json();if(!r.ok)throw Error(b.error);setRuns(x=>[b,...x]);}catch(e){setError(e instanceof Error?e.message:'Scenario failed');}finally{setBusy('');}}
return <><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{safetyScenarios.map(s=><button key={s} disabled={!!busy} onClick={()=>void run(s)} className="card p-4 text-left hover:border-brand-300"><div className="flex items-center justify-between"><ShieldAlert size={17} className="text-brand-600"/><Play size={13}/></div><p className="mt-3 text-sm font-semibold">{names[s]}</p><p className="mt-1 text-xs text-slate-500">Run controlled mock fault</p></button>)}</div>{error&&<p className="callout callout-danger mt-4">{error}</p>}<div className="mt-7 space-y-4">{runs.map(r=><article key={r.id} className="card p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="page-eyebrow">{names[r.scenario as SafetyScenario]??r.scenario}</p><h3 className="font-semibold text-slate-900">{r.injected}</h3></div><span className={r.passed?'badge-success':'badge-danger'}>{r.passed?'PASS':'FAIL'}</span></div><p className="mt-3 text-sm"><strong>Expected invariant:</strong> {r.expectedInvariant}</p><div className="mt-4 grid gap-3 sm:grid-cols-4">{[['Requests',r.requestsReceived],['Accepted',r.accepted],['Duplicates blocked',r.duplicatesRejected],['Provider actions',r.providerActions]].map(([k,v])=><div key={k} className="rounded-lg bg-slate-50 p-3"><p className="text-[10px] uppercase text-slate-500">{k}</p><p className="text-xl font-bold">{v}</p></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{(JSON.parse(r.timeline) as string[]).map(x=><span key={x} className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-3 py-1 text-xs text-emerald-800"><CheckCircle2 size={12}/>{x}</span>)}</div><p className="mt-4 text-xs text-slate-500">Final state: {r.finalState} · {r.auditEvents} audit events</p></article>)}</div></>}
