'use client';

import {useState} from 'react';
import Link from 'next/link';
import {AlertTriangle,CheckCircle2,Play,ScrollText} from 'lucide-react';
import {inr} from '@/lib/currency';

type BatchItem={id:string;recoveryCaseId:string;action:string;result:string;recoveredAmount:number;detail:string|null};
type Batch={id:string;status:string;casesEvaluated:number;actionsExecuted:number;confirmedRecoveryCount:number;confirmedRecoveryAmount:number;declinedOrUnresolved:number;blockedByPolicy:number;unsafeActionsPrevented:number;requiresApproval:number;createdAt:string|Date;items:BatchItem[]};
const metricLabels:[keyof Batch,string][]=[['casesEvaluated','Cases evaluated'],['actionsExecuted','Actions executed'],['confirmedRecoveryCount','Confirmed recoveries'],['confirmedRecoveryAmount','Confirmed amount'],['declinedOrUnresolved','Declined or unresolved'],['blockedByPolicy','Blocked by policy'],['unsafeActionsPrevented','Unsafe actions prevented'],['requiresApproval','Requires approval']];

export function SafeDemoBatchPanel({initial}:{initial:Batch[]}){
 const [batches,setBatches]=useState(initial),[confirming,setConfirming]=useState(false),[running,setRunning]=useState(false),[error,setError]=useState('');
 const latest=batches[0];
 async function run(){setRunning(true);setError('');try{const response=await fetch('/api/safe-demo-batch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID()})});const body=await response.json();if(!response.ok)throw Error(body.error);setBatches(current=>[body,...current.filter(batch=>batch.id!==body.id)]);setConfirming(false);}catch(cause){setError(cause instanceof Error?cause.message:'Safe demo batch could not be completed');}finally{setRunning(false);}}
 return <section className="card card-static mt-7 p-6" aria-labelledby="safe-demo-heading">
  <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="page-eyebrow">Mock demonstration evidence</p><h3 id="safe-demo-heading" className="text-xl font-semibold text-slate-900">Safe Demo Batch</h3><p className="mt-1 max-w-2xl text-sm text-slate-500">Evaluate up to 20 current mock cases through the real recovery execution path. Approval, scheduling and every hard safety gate remain active.</p></div>{!confirming&&<button className="btn-primary" onClick={()=>setConfirming(true)}><Play size={14}/>Run safe demo batch</button>}</div>
  {confirming&&<div className="callout callout-warning mt-5 items-start"><AlertTriangle size={16} className="mt-0.5 shrink-0"/><div className="flex-1"><p className="font-semibold">Confirm mock batch execution</p><p className="mt-1 text-xs">This can execute eligible mock retries and create mock payment links. It will not approve cases, ignore schedules, confirm link payments or contact Razorpay.</p><div className="mt-3 flex gap-2"><button className="btn-warning" disabled={running} onClick={()=>void run()}>{running?'Running safely…':'Confirm and run'}</button><button className="btn-ghost" disabled={running} onClick={()=>setConfirming(false)}>Cancel</button></div></div></div>}
  {error&&<div className="callout callout-danger mt-4" role="alert">{error}</div>}
  {latest?<div className="mt-6"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-mono text-xs text-slate-500">Batch {latest.id}</p><Link href={`/audit?q=${encodeURIComponent(latest.id)}`} className="inline-flex items-center gap-1 text-xs font-semibold text-brand-700 hover:underline"><ScrollText size={13}/>View batch audit evidence</Link></div><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{metricLabels.map(([key,label])=><div key={key} className="rounded-xl border border-slate-200 bg-slate-50 p-3"><dt className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 text-lg font-bold tabular-nums text-slate-900">{key==='confirmedRecoveryAmount'?inr(latest[key] as number):latest[key] as number}</dd></div>)}</dl>{latest.casesEvaluated===0?<div className="mt-4 rounded-xl border border-dashed border-slate-200 p-5 text-sm text-slate-500">No current mock cases were eligible for batch evaluation. Safety rules were left unchanged and no result was invented.</div>:<div className="mt-5 overflow-x-auto"><table className="data-table"><thead><tr><th>Recovery case</th><th>Action</th><th>Result</th><th>Confirmed amount</th></tr></thead><tbody>{latest.items.map(item=><tr key={item.id}><td><Link href={`/recoveries/${item.recoveryCaseId}`} className="font-mono text-xs font-semibold text-brand-700 hover:underline">{item.recoveryCaseId}</Link></td><td>{item.action}</td><td><p className="font-semibold">{item.result.replaceAll('_',' ')}</p><p className="text-xs text-slate-500">{item.detail}</p></td><td>{inr(item.recoveredAmount)}</td></tr>)}</tbody></table></div>}<p className="mt-4 flex items-center gap-1 text-xs text-slate-500"><CheckCircle2 size={13} className="text-emerald-600"/>Only persisted confirmed mock-provider outcomes are included in recovered revenue. Created payment links remain pending.</p></div>:<p className="mt-5 text-sm text-slate-500">No Safe Demo Batch has been run yet.</p>}
 </section>;
}
